from __future__ import annotations

import inspect
import json
import os
import re
import shutil
import subprocess
import tempfile
import threading
import time
from collections import OrderedDict, deque
from pathlib import Path
from queue import Empty, Queue
from typing import Any, Protocol

from .candidate import apply_candidate
from .model import CandidateTransition, GateReceipt, Move, Position
from .query import BuiltQuery, LitexQueryBuilder


class Gate(Protocol):
    def validate_move(self, position: Position, move: Move) -> tuple[CandidateTransition, GateReceipt]: ...
    def validate_position(self, position: Position) -> GateReceipt: ...
    def health(self) -> dict[str, Any]: ...
    def close(self) -> None: ...


def _bundled_litex_binary() -> str | None:
    """Return the packaged official Litex executable for this platform."""
    root = Path(__file__).resolve().parents[2]
    if os.name == "nt":
        candidates = [root / "tools" / "litex" / "windows-amd64" / "litex.exe"]
    else:
        candidates = [root / "tools" / "litex" / "linux-amd64" / "litex"]
    for candidate in candidates:
        if candidate.is_file():
            # ZIP extraction can lose the Unix executable bit.  Restoring it is
            # safe here because the file is an explicitly bundled executable.
            if os.name != "nt" and not os.access(candidate, os.X_OK):
                try:
                    candidate.chmod(candidate.stat().st_mode | 0o111)
                except OSError:
                    continue
            if os.name == "nt" or os.access(candidate, os.X_OK):
                return str(candidate)
    return None


def _walk_results(value: Any):
    if isinstance(value, dict):
        yield value
        for item in value.get("inside_results", []) or []:
            yield from _walk_results(item)
        previous = value.get("previous_error")
        if previous is not None:
            yield from _walk_results(previous)
    elif isinstance(value, list):
        for item in value:
            yield from _walk_results(item)


def results_successful(results: list[dict[str, Any]]) -> bool:
    walked = list(_walk_results(results))
    return bool(walked) and all(item.get("result") == "success" for item in walked)


def compact_results(results: list[dict[str, Any]], limit: int = 12) -> list[dict[str, Any]]:
    compact: list[dict[str, Any]] = []
    for item in _walk_results(results):
        row = {
            key: item[key]
            for key in ("result", "type", "stmt", "message", "error", "line")
            if key in item
        }
        if row:
            compact.append(row)
        if len(compact) >= limit:
            break
    return compact


def diagnostics_from_results(results: list[dict[str, Any]], limit: int = 8) -> list[str]:
    diagnostics: list[str] = []
    for item in _walk_results(results):
        if item.get("result") == "success":
            continue
        for key in ("message", "error", "stmt"):
            value = item.get(key)
            if value:
                diagnostics.append(str(value))
                break
        if len(diagnostics) >= limit:
            break
    return diagnostics


class _LRU:
    def __init__(self, maxsize: int = 512) -> None:
        self.maxsize = maxsize
        self._data: OrderedDict[str, GateReceipt] = OrderedDict()

    def get(self, key: str) -> GateReceipt | None:
        value = self._data.get(key)
        if value is not None:
            self._data.move_to_end(key)
        return value

    def put(self, key: str, value: GateReceipt) -> None:
        self._data[key] = value
        self._data.move_to_end(key)
        while len(self._data) > self.maxsize:
            self._data.popitem(last=False)


class SessionLitexGate:
    """Low-latency official Litex framed session transport.

    The formal kernel is loaded once with ``litex -session -f``.  Every concrete
    certificate is submitted as an outermost ``try:`` block, so a rejected
    certificate is rolled back and the verifier process remains usable.  The
    submitted certificate is generated by the same deterministic builder as the
    one-shot gate; no Python chess engine can authorize a move.
    """

    _PROP_CALL = re.compile(r"\$([A-Za-z_][A-Za-z0-9_]*)\(")

    def __init__(
        self,
        builder: LitexQueryBuilder,
        formal_path: str | Path,
        binary: str = "litex",
        timeout: float = 30.0,
        include_source: bool = False,
        restart_after: int = 2000,
    ) -> None:
        self.builder = builder
        self.formal_path = Path(formal_path).resolve()
        self.binary = binary
        self.timeout = timeout
        self.include_source = include_source
        self.restart_after = max(1, restart_after)
        self.namespace = self._discover_namespace(self.formal_path)
        self._lock = threading.RLock()
        self._cache = _LRU(maxsize=2048)
        self._counter = 0
        self._blocks_since_restart = 0
        self._process: subprocess.Popen[bytes] | None = None
        self._events: Queue[bytes | None] = Queue()
        self._stderr_tail: deque[str] = deque(maxlen=50)
        self._reader: threading.Thread | None = None
        self._stderr_reader: threading.Thread | None = None
        started = time.perf_counter()
        self._start_process()
        self._boot_ms = (time.perf_counter() - started) * 1000

    @staticmethod
    def _discover_namespace(formal_path: Path) -> str:
        """Find the export name for the formal file, falling back to its stem."""
        config = formal_path.parent / "litex.config"
        if config.is_file():
            in_export = False
            target = formal_path.resolve()
            for raw in config.read_text(encoding="utf-8").splitlines():
                line = raw.strip()
                if line.startswith("[") and line.endswith("]"):
                    in_export = line.lower() == "[export]"
                    continue
                if not in_export or not line or line.startswith("#") or "=" not in line:
                    continue
                name, value = line.split("=", 1)
                literal = value.strip().strip('"').strip("'")
                candidate = (config.parent / literal).resolve()
                if candidate == target:
                    return name.strip()
        return formal_path.stem

    @staticmethod
    def _parse_json_objects(text: str) -> list[dict[str, Any]]:
        decoder = json.JSONDecoder()
        results: list[dict[str, Any]] = []
        index = 0
        while index < len(text):
            if text[index] != "{":
                index += 1
                continue
            try:
                value, offset = decoder.raw_decode(text[index:])
            except ValueError:
                index += 1
                continue
            if isinstance(value, dict):
                results.append(value)
            index += max(offset, 1)
        return results

    def _stdout_loop(self, stream: Any) -> None:
        try:
            while True:
                line = stream.readline()
                if not line:
                    break
                self._events.put(line)
        finally:
            self._events.put(None)

    def _stderr_loop(self, stream: Any) -> None:
        while True:
            line = stream.readline()
            if not line:
                return
            self._stderr_tail.append(line.decode("utf-8", errors="replace").rstrip())

    def _next_event(self) -> dict[str, Any]:
        try:
            line = self._events.get(timeout=self.timeout)
        except Empty as exc:
            raise TimeoutError("timed out waiting for a Litex session event") from exc
        if line is None:
            detail = "\n".join(self._stderr_tail)
            raise RuntimeError("Litex session closed unexpectedly" + (f": {detail}" if detail else ""))
        try:
            event = json.loads(line.decode("utf-8"))
        except Exception as exc:
            raise RuntimeError(f"malformed Litex session event: {line[-1000:]!r}") from exc
        if not isinstance(event, dict):
            raise RuntimeError(f"unexpected Litex session event: {event!r}")
        return event

    def _start_process(self) -> None:
        self._events = Queue()
        self._stderr_tail.clear()
        command = [
            self.binary,
            "-compact",
            "-session",
            "-f",
            str(self.formal_path),
        ]
        self._process = subprocess.Popen(
            command,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            bufsize=0,
        )
        assert self._process.stdout is not None
        assert self._process.stderr is not None
        self._reader = threading.Thread(
            target=self._stdout_loop,
            args=(self._process.stdout,),
            name="litex-session-stdout",
            daemon=True,
        )
        self._stderr_reader = threading.Thread(
            target=self._stderr_loop,
            args=(self._process.stderr,),
            name="litex-session-stderr",
            daemon=True,
        )
        self._reader.start()
        self._stderr_reader.start()
        event = self._next_event()
        if event.get("event") != "ready":
            self._stop_process()
            raise RuntimeError(f"Litex session startup failed: {event!r}")
        self._blocks_since_restart = 0

    def _stop_process(self) -> None:
        process = self._process
        self._process = None
        if process is None:
            return
        if process.poll() is None and process.stdin is not None:
            try:
                process.stdin.write(b"close\n")
                process.stdin.flush()
            except OSError:
                pass
        try:
            process.wait(timeout=2)
        except subprocess.TimeoutExpired:
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=2)
        for stream in (process.stdin, process.stdout, process.stderr):
            if stream is not None:
                try:
                    stream.close()
                except OSError:
                    pass

    def _qualify_and_wrap(self, source: str) -> str:
        namespace = self.namespace
        qualified = self._PROP_CALL.sub(
            lambda match: f"${namespace}::{match.group(1)}(",
            source,
        )
        # Algebraic square names and result names are declared locally in the
        # query (for example ``have e2 Z = 12``), so only predicate names need
        # module qualification in a persistent session.
        indented = "\n".join(
            ("    " + line) if line else ""
            for line in qualified.rstrip().splitlines()
        )
        # The deliberate final contradiction makes every top-level try block
        # fail and therefore roll back. If and only if all certificate lines
        # succeeded, the first failing statement is this sentinel.
        return f"try:\n{indented}\n    0 = 1\n"

    def _run_block(self, query: BuiltQuery) -> tuple[dict[str, Any], list[dict[str, Any]]]:
        if self._blocks_since_restart >= self.restart_after:
            self._stop_process()
            self._start_process()
        process = self._process
        if process is None or process.poll() is not None or process.stdin is None:
            raise RuntimeError("Litex session is not running")
        self._counter += 1
        block_id = f"chess-{self._counter}"
        payload = self._qualify_and_wrap(query.source).encode("utf-8")
        process.stdin.write(f"run {block_id} {len(payload)}\n".encode("ascii"))
        process.stdin.write(payload)
        process.stdin.flush()
        event = self._next_event()
        self._blocks_since_restart += 1
        if event.get("event") != "block" or event.get("id") != block_id:
            raise RuntimeError(f"unexpected Litex session response: {event!r}")
        trace = event.get("trace", "")
        results = self._parse_json_objects(trace) if isinstance(trace, str) else []
        return event, results

    def _execute(self, query: BuiltQuery) -> GateReceipt:
        cached = self._cache.get(query.sha256)
        if cached is not None:
            return GateReceipt(
                accepted=cached.accepted,
                engine="litex/persistent-session+cache",
                query_sha256=cached.query_sha256,
                elapsed_ms=0.0,
                reason=cached.reason,
                results=cached.results,
                diagnostics=cached.diagnostics,
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )

        started = time.perf_counter()
        try:
            with self._lock:
                event, results = self._run_block(query)
            elapsed = (time.perf_counter() - started) * 1000
            sentinel_reached = any(
                item.get("result") != "success" and item.get("statement") == "0 = 1"
                for item in _walk_results(results)
            )
            # A successful certificate deliberately ends in 0 = 1, causing the
            # outer try to fail and discard all temporary facts. An earlier
            # certificate failure never reaches this sentinel.
            accepted = event.get("ok") is False and sentinel_reached
            if accepted:
                diagnostics: list[str] = []
                reason = "all Litex certificate statements succeeded; transactional rollback sentinel reached"
                receipt_results = [{"result": "success", "type": "transactional certificate"}]
            else:
                diagnostics = diagnostics_from_results(results)
                reason = (
                    "Litex refuted or could not establish the move certificate"
                    if diagnostics
                    else "Litex session rejected the certificate without a structured diagnostic"
                )
                receipt_results = compact_results(results)
            receipt = GateReceipt(
                accepted=accepted,
                engine="litex/persistent-session",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason=reason,
                results=receipt_results,
                diagnostics=diagnostics,
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        except Exception as exc:
            elapsed = (time.perf_counter() - started) * 1000
            # The worker is no longer trusted after a transport/protocol failure.
            with self._lock:
                self._stop_process()
                try:
                    self._start_process()
                except Exception as restart_exc:
                    self._stderr_tail.append(f"restart failed: {type(restart_exc).__name__}: {restart_exc}")
            receipt = GateReceipt(
                accepted=False,
                engine="litex/persistent-session",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason="Litex session failed; fail-closed rejection",
                diagnostics=[f"{type(exc).__name__}: {exc}"] + list(self._stderr_tail)[-3:],
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        self._cache.put(query.sha256, receipt)
        return receipt

    def validate_move(self, position: Position, move: Move) -> tuple[CandidateTransition, GateReceipt]:
        transition = apply_candidate(position, move)
        return transition, self._execute(self.builder.build_move_query(transition))

    def validate_position(self, position: Position) -> GateReceipt:
        return self._execute(self.builder.build_position_query(position))

    def health(self) -> dict[str, Any]:
        process = self._process
        return {
            "ready": process is not None and process.poll() is None,
            "engine": "litex/persistent-session",
            "boot_ms": round(self._boot_ms, 3),
            "namespace": self.namespace,
            "blocks_since_restart": self._blocks_since_restart,
        }

    def close(self) -> None:
        with self._lock:
            self._stop_process()


class LitexPyGate:
    """Persistent official litexpy runner. No non-Litex fallback is used."""

    def __init__(
        self,
        builder: LitexQueryBuilder,
        command: list[str] | None = None,
        timeout: float = 30.0,
        include_source: bool = False,
    ) -> None:
        try:
            import litexpy  # type: ignore
        except Exception as exc:  # pragma: no cover - environment dependent
            raise RuntimeError("litexpy is not installed") from exc
        self.builder = builder
        self.timeout = timeout
        self.include_source = include_source
        self._lock = threading.RLock()
        self._cache = _LRU()
        self._runner = self._construct_runner(litexpy.Runner, command, timeout)
        start = time.perf_counter()
        results = self._call_runner(self._runner.run, builder.formal_source, timeout)
        self._boot_ms = (time.perf_counter() - start) * 1000
        self._boot_results = compact_results(results)
        if not results_successful(results):
            close = getattr(self._runner, "close", None)
            if callable(close):
                close()
            raise RuntimeError(
                "Litex rejected formal/chess_rules.lit: "
                + "; ".join(diagnostics_from_results(results))
            )

    @staticmethod
    def _construct_runner(runner_type: Any, command: list[str] | None, timeout: float) -> Any:
        """Adapt to the small constructor changes across litexpy beta releases."""
        signature = inspect.signature(runner_type)
        params = signature.parameters
        kwargs: dict[str, Any] = {}
        if command is not None:
            for name in ("command", "cmd", "litex_command"):
                if name in params:
                    kwargs[name] = command
                    break
        for name in ("run_timeout", "timeout"):
            if name in params:
                kwargs[name] = timeout
                break
        try:
            return runner_type(**kwargs)
        except TypeError:
            # The published API also supports a zero-argument local `litex` runner.
            return runner_type()

    @staticmethod
    def _call_runner(method: Any, source: str, timeout: float, *, sandbox: bool = False) -> Any:
        signature = inspect.signature(method)
        params = signature.parameters
        kwargs: dict[str, Any] = {}
        for name in ("timeout", "run_timeout"):
            if name in params:
                kwargs[name] = timeout
                break
        if sandbox and "commit" in params:
            kwargs["commit"] = False
        return method(source, **kwargs)

    def _execute(self, query: BuiltQuery) -> GateReceipt:
        cached = self._cache.get(query.sha256)
        if cached is not None:
            return GateReceipt(
                accepted=cached.accepted,
                engine=cached.engine + "+cache",
                query_sha256=cached.query_sha256,
                elapsed_ms=0.0,
                reason=cached.reason,
                results=cached.results,
                diagnostics=cached.diagnostics,
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        started = time.perf_counter()
        try:
            with self._lock:
                results = self._call_runner(self._runner.sandbox_run, query.source, self.timeout, sandbox=True)
            elapsed = (time.perf_counter() - started) * 1000
            accepted = results_successful(results)
            receipt = GateReceipt(
                accepted=accepted,
                engine="litexpy/persistent-sandbox",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason=(
                    "all Litex statements returned success"
                    if accepted
                    else "Litex did not establish the requested proposition"
                ),
                results=compact_results(results),
                diagnostics=diagnostics_from_results(results),
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        except Exception as exc:
            elapsed = (time.perf_counter() - started) * 1000
            receipt = GateReceipt(
                accepted=False,
                engine="litexpy/persistent-sandbox",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason="Litex execution failed; fail-closed rejection",
                diagnostics=[f"{type(exc).__name__}: {exc}"],
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        self._cache.put(query.sha256, receipt)
        return receipt

    def validate_move(self, position: Position, move: Move) -> tuple[CandidateTransition, GateReceipt]:
        transition = apply_candidate(position, move)
        return transition, self._execute(self.builder.build_move_query(transition))

    def validate_position(self, position: Position) -> GateReceipt:
        return self._execute(self.builder.build_position_query(position))

    def health(self) -> dict[str, Any]:
        return {
            "ready": True,
            "engine": "litexpy/persistent-sandbox",
            "boot_ms": round(self._boot_ms, 3),
            "boot_results": self._boot_results,
        }

    def close(self) -> None:
        with self._lock:
            close = getattr(self._runner, "close", None)
            if callable(close):
                close()
            else:
                clear = getattr(self._runner, "clear", None)
                if callable(clear):
                    clear()


class SubprocessLitexGate:
    """One-shot Litex CLI adapter used for CI and as a Litex-only backup transport."""

    def __init__(
        self,
        builder: LitexQueryBuilder,
        binary: str = "litex",
        timeout: float = 45.0,
        include_source: bool = False,
    ) -> None:
        self.builder = builder
        self.binary = binary
        self.timeout = timeout
        self.include_source = include_source
        self._cache = _LRU(maxsize=256)
        probe = subprocess.run(
            [binary, "-version"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
            check=False,
        )
        if probe.returncode != 0:
            raise RuntimeError(f"cannot start Litex binary {binary!r}: {probe.stdout}")
        self.version_output = probe.stdout.strip()

    @staticmethod
    def _parse_json_objects(text: str) -> list[dict[str, Any]]:
        decoder = json.JSONDecoder()
        results: list[dict[str, Any]] = []
        index = 0
        while index < len(text):
            if text[index] != "{":
                index += 1
                continue
            try:
                value, offset = decoder.raw_decode(text[index:])
            except ValueError:
                index += 1
                continue
            if isinstance(value, dict):
                results.append(value)
            index += max(offset, 1)
        return results

    def _execute(self, query: BuiltQuery) -> GateReceipt:
        cached = self._cache.get(query.sha256)
        if cached is not None:
            return cached
        standalone = self.builder.as_standalone(query)
        started = time.perf_counter()
        try:
            with tempfile.TemporaryDirectory(prefix="litex-chess-") as tmp:
                project = Path(tmp)
                entry = project / "entry.lit"
                entry.write_text(standalone, encoding="utf-8")
                (project / "litex.config").write_text(
                    '[hierarchy]\nmodule\n\n[export]\nentry = "./entry.lit"\n',
                    encoding="utf-8",
                )
                process = subprocess.run(
                    [self.binary, "-compact", "-runner", "-f", str(entry)],
                    text=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    timeout=self.timeout,
                    check=False,
                )

            elapsed = (time.perf_counter() - started) * 1000
            wrappers = self._parse_json_objects(process.stdout)
            wrapper = wrappers[-1] if wrappers else {}
            trace_text = wrapper.get("trace", "") if isinstance(wrapper, dict) else ""
            results = self._parse_json_objects(trace_text) if isinstance(trace_text, str) else []
            wrapper_ok = bool(wrapper.get("ok")) if isinstance(wrapper, dict) else False
            accepted = process.returncode == 0 and wrapper_ok and results_successful(results)
            diagnostics = diagnostics_from_results(results)
            if not diagnostics and not accepted:
                if isinstance(wrapper, dict) and wrapper.get("error"):
                    diagnostics = [str(wrapper.get("error"))]
                else:
                    diagnostics = [process.stdout[-4000:] or f"exit code {process.returncode}"]
            receipt = GateReceipt(
                accepted=accepted,
                engine="litex/one-shot-runner",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason=(
                    "all Litex statements returned success"
                    if accepted
                    else "Litex runner rejected or could not establish the certificate"
                ),
                results=compact_results(results),
                diagnostics=diagnostics,
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        except Exception as exc:
            elapsed = (time.perf_counter() - started) * 1000
            receipt = GateReceipt(
                accepted=False,
                engine="litex/one-shot-runner",
                query_sha256=query.sha256,
                elapsed_ms=elapsed,
                reason="Litex execution failed; fail-closed rejection",
                diagnostics=[f"{type(exc).__name__}: {exc}"],
                formal_source=query.source if self.include_source else None,
                agent_source=query.agent_source if self.include_source else None,
                query_kind=query.kind,
                board_transition_mode=query.board_transition_mode,
                outcome=query.outcome,
                checker_count=query.checker_count,
                legal_reply_count=query.legal_reply_count,
            )
        self._cache.put(query.sha256, receipt)
        return receipt

    def validate_move(self, position: Position, move: Move) -> tuple[CandidateTransition, GateReceipt]:
        transition = apply_candidate(position, move)
        return transition, self._execute(self.builder.build_move_query(transition))

    def validate_position(self, position: Position) -> GateReceipt:
        return self._execute(self.builder.build_position_query(position))

    def health(self) -> dict[str, Any]:
        return {
            "ready": True,
            "engine": "litex/one-shot-cli",
            "version": self.version_output,
        }

    def close(self) -> None:
        return None


class UnavailableGate:
    """Explicit fail-closed object returned when no Litex transport starts."""

    def __init__(self, diagnostics: list[str], include_source: bool = False) -> None:
        self.diagnostics = diagnostics
        self.include_source = include_source

    def _receipt(self, sha: str = "unavailable", source: str | None = None) -> GateReceipt:
        return GateReceipt(
            accepted=False,
            engine="litex/unavailable",
            query_sha256=sha,
            elapsed_ms=0.0,
            reason="Litex is unavailable; the application never falls back to another rules engine",
            diagnostics=self.diagnostics,
            formal_source=source if self.include_source else None,
        )

    def validate_move(self, position: Position, move: Move) -> tuple[CandidateTransition, GateReceipt]:
        return apply_candidate(position, move), self._receipt()

    def validate_position(self, position: Position) -> GateReceipt:
        return self._receipt()

    def health(self) -> dict[str, Any]:
        return {"ready": False, "engine": "litex/unavailable", "diagnostics": self.diagnostics}

    def close(self) -> None:
        return None


def create_gate(
    formal_path: str | Path,
    timeout: float = 30.0,
    include_source: bool = False,
) -> Gate:
    builder = LitexQueryBuilder.from_file(formal_path)
    diagnostics: list[str] = []

    binary = (
        os.environ.get("LITEXPY_LITEX_BIN")
        or os.environ.get("LITEX_BIN")
        or _bundled_litex_binary()
        or "litex"
    )
    command_env = os.environ.get("LITEXPY_LITEX_COMMAND")
    command: list[str] | None = None
    if command_env:
        import shlex

        command = shlex.split(command_env)
    elif binary != "litex":
        command = [binary]

    try:
        return SessionLitexGate(
            builder,
            formal_path=formal_path,
            binary=binary,
            timeout=timeout,
            include_source=include_source,
        )
    except Exception as exc:
        diagnostics.append(f"framed session: {type(exc).__name__}: {exc}")

    # Compatibility fallback for older Litex versions that do not expose the
    # framed session protocol. Note that litexpy.sandbox_run() creates a fresh
    # sandbox process, so it is a correctness-preserving fallback, not the fast path.
    try:
        return LitexPyGate(
            builder,
            command=command,
            timeout=timeout,
            include_source=include_source,
        )
    except Exception as exc:
        diagnostics.append(f"litexpy sandbox: {type(exc).__name__}: {exc}")

    try:
        return SubprocessLitexGate(
            builder,
            binary=binary,
            timeout=max(timeout, 45.0),
            include_source=include_source,
        )
    except Exception as exc:
        diagnostics.append(f"one-shot CLI: {type(exc).__name__}: {exc}")
    return UnavailableGate(diagnostics, include_source=include_source)
